// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwS4sWNcK4PQr1b7bFo08kOfVvR0Hfynw',
    appId: '1:734146615949:web:ce7614f5da86294daee0c4',
    messagingSenderId: '734146615949',
    projectId: 'todo-list-uniube',
    authDomain: 'todo-list-uniube.firebaseapp.com',
    databaseURL: 'https://todo-list-uniube-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-uniube.firebasestorage.app',
    measurementId: 'G-6CCYWC07RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Y-5oTSnC9zrJLtygTAWusWRWcMAO9c4',
    appId: '1:734146615949:android:1ffaa3d840025b1daee0c4',
    messagingSenderId: '734146615949',
    projectId: 'todo-list-uniube',
    databaseURL: 'https://todo-list-uniube-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-uniube.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXKXFUuupWph69kotVGOKIYoEVLQ3F3g',
    appId: '1:734146615949:ios:89b03f9637542b2baee0c4',
    messagingSenderId: '734146615949',
    projectId: 'todo-list-uniube',
    databaseURL: 'https://todo-list-uniube-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-uniube.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXKXFUuupWph69kotVGOKIYoEVLQ3F3g',
    appId: '1:734146615949:ios:89b03f9637542b2baee0c4',
    messagingSenderId: '734146615949',
    projectId: 'todo-list-uniube',
    databaseURL: 'https://todo-list-uniube-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-uniube.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwS4sWNcK4PQr1b7bFo08kOfVvR0Hfynw',
    appId: '1:734146615949:web:9fb1945ff6148d4caee0c4',
    messagingSenderId: '734146615949',
    projectId: 'todo-list-uniube',
    authDomain: 'todo-list-uniube.firebaseapp.com',
    databaseURL: 'https://todo-list-uniube-default-rtdb.firebaseio.com',
    storageBucket: 'todo-list-uniube.firebasestorage.app',
    measurementId: 'G-3M9KGR9TSQ',
  );
}
